config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :users
  resources :discussions
  resources :topics
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  post "users/change" => "users#change"
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user
  belongs_to :topic

  validates :topic_id, :user_id, :message, presence: true

  after_create_commit -> { broadcast_append_to "topic_discussion_socket", partial: "topics/topic_discussion", target: "topic_#{self.topic_id}_discussions_container" }
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: %i[ show edit update destroy ]

  # GET /discussions or /discussions.json
  def index
    @discussions = Discussion.all
  end

  # GET /discussions/1 or /discussions/1.json
  def show
  end

  # GET /discussions/new
  def new
    @discussion = Discussion.new
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions or /discussions.json
  def create
    @discussion = Discussion.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to topics_path }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1 or /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: "Discussion was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1 or /discussions/1.json
  def destroy
    @discussion.destroy!

    respond_to do |format|
      format.html { redirect_to discussions_path, notice: "Discussion was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = Discussion.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def discussion_params
      params.expect(discussion: [ :topic_id, :user_id, :message ])
    end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_discussion.html.erb
<div id="<%= dom_id discussion %>">
  <p>
    <strong>Topic:</strong>
    <%= discussion.topic_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= discussion.user_id %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= discussion.message %>
  </p>

</div>

app/views/discussions/_form.html.erb
<%= form_with(model: discussion) do |form| %>
  <% if discussion.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
        <% discussion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :topic_id, style: "display: block" %>
    <%= form.number_field :topic_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.textarea :message %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<% content_for :title, "Editing discussion" %>

<h1>Editing discussion</h1>

<%= render "form", discussion: @discussion %>

<br>

<div>
  <%= link_to "Show this discussion", @discussion %> |
  <%= link_to "Back to discussions", discussions_path %>
</div>

app/views/discussions/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Discussions" %>

<h1>Discussions</h1>

<div id="discussions">
  <% @discussions.each do |discussion| %>
    <%= render discussion %>
    <p>
      <%= link_to "Show this discussion", discussion %>
    </p>
  <% end %>
</div>

<%= link_to "New discussion", new_discussion_path %>

app/views/discussions/new.html.erb
<% content_for :title, "New discussion" %>

<h1>New discussion</h1>

<%= render "form", discussion: @discussion %>

<br>

<div>
  <%= link_to "Back to discussions", discussions_path %>
</div>

app/views/discussions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @discussion %>

<div>
  <%= link_to "Edit this discussion", edit_discussion_path(@discussion) %> |
  <%= link_to "Back to discussions", discussions_path %>

  <%= button_to "Destroy this discussion", @discussion, method: :delete %>
</div>