config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :users
  resources :discussions
  resources :topics
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  post "users/change" => "users#change"
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :discussions, dependent: :destroy
  belongs_to :user

  validates :user_id, :title, :content, presence: true

  after_destroy_commit -> { broadcast_remove_to "topics_socket", target: "topic_#{self.id}" }
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.includes(:user, discussions: :user ).order(id: :desc)
    @reply = Discussion.new
  end

  # GET /topics/1 or /topics/1.json
  def show
    @reply = Discussion.new
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: "Topic was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy!

    respond_to do |format|
      format.html { redirect_to topics_path, notice: "Topic was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.expect(topic: [ :user_id, :title, :content ])
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_with(model: topic) do |form| %>
  <%= form.hidden_field :user_id, value: session[:current_user]["id"] %>

  <% if topic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.textarea :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div class="row mb-4">
  <div class="col-md-6">
    <h2><%= topic.title %></h2>
  </div>

  <div class="col-md-6 text-end">
    <h3><%= topic.user.username %></h3>
  </div>
</div>
<div class="row mb-4">
  <div class="col-md-12 fs-5">
    <p><%= topic.content %></p>
  </div>
</div>

<div class="row mb-4">
  <div class="col-md-12">
    <div class="bg-body border rounded-3 p-3">

      <%= turbo_stream_from "topic_discussion_socket" %>
      <div id="<%= "topic_#{topic.id}_discussions_container" %>">
        <% topic.discussions.each do |discussion| %>
          <%= render "topic_discussion", discussion: discussion %>
        <% end %>
      </div>

      <hr class="my-4">

      <% if @reply %>
        <div id="reply_discussion" class="px-3">
          <%= render "topic_discussion_form", reply: @reply, topic: topic %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/topics/_topic_discussion.html.erb
<div id="<%= dom_id discussion %>" class="px-3">
  <p>
    <strong><%= discussion.user.username %>: </strong><%= discussion.message %>
  </p>
</div>

app/views/topics/_topic_discussion_form.html.erb
<%= form_with(model: reply) do |form| %>
  <%= form.hidden_field :topic_id, value: topic.id %>
  <%= form.hidden_field :user_id, value: session[:current_user]["id"] %>

  <div class="row mb-3">
    <%= form.label :message, session[:current_user]["username"] + ": ", class: "col-sm-3 col-form-label fw-bold  text-end" %>

    <div class="col-sm-7">
      <%= form.textarea :message, class: "form-control" %>
    </div>

    <div class="col-sm-2 text-end">
      <%= form.submit "Responder", class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/topics/edit.html.erb
<% content_for :title, "Editing topic" %>

<h1>Editing topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Show this topic", @topic %> |
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/index.html.erb
<div class="row">
  <div class="col-md-12 text-end">
    <%= link_to "Crear", new_topic_path, class: "btn btn-primary" %>
  </div>
</div>

<%= turbo_stream_from "topics_socket" %>
<% @topics.each do |topic| %>
  <div id="topics_container">
    <div id="<%= dom_id topic %>">
      <div class="row align-items-md-stretch">
        <div class="col-md-12">
          <div class="px-5 pt-5">
            <div class="h-100 p-5 bg-light border rounded-3">
              <%= render "topics/topic", topic: topic %>
              <div class="row">
                <div class="col-md-12 text-end">
                  <%= link_to "Ver", topic, class: "btn btn-primary" %>
                  <% if topic.user_id == session[:current_user]["id"] %>
                    <%= link_to "Eliminar", topic, class: "btn btn-danger", data: { turbo_method: :delete } %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/topics/new.html.erb
<% content_for :title, "New topic" %>

<h1>New topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/show.html.erb
<div class="row">
    <p style="color: green"><%= notice %></p>
</div>

<div class="row">
    <%= render @topic %>
</div>

<div>
  <%= link_to "Edit this topic", edit_topic_path(@topic) %> |
  <%= link_to "Back to topics", topics_path %>

  <%= button_to "Destroy this topic", @topic, method: :delete %>
</div>